spring.application.name=hotelBooking

#DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=sumanbaral
spring.datasource.password=suman12345
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1